# Generated by Django 2.2.3 on 2019-07-22 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('jabatan', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mata_pelajaran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelajaran', models.CharField(max_length=50)),
                ('jadwal_dimulai', models.DateField()),
                ('jadwal_berakhir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('nomor_absen', models.CharField(max_length=10)),
                ('nilai_rata_rata', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.TextField(max_length=100)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Live_code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_live_code', models.CharField(max_length=50)),
                ('banyak_soal', models.CharField(max_length=50)),
                ('bobot_nilai', models.CharField(max_length=50)),
                ('tanggal_pelaksanaan', models.DateField()),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_pelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_challenge', models.CharField(max_length=50)),
                ('banyak_soal', models.CharField(max_length=50)),
                ('bobot_nilai', models.CharField(max_length=50)),
                ('mata_pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ATA.Mata_pelajaran')),
            ],
        ),
    ]
