# Generated by Django 2.2.3 on 2019-07-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Rumah_sakit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kandungan', models.TextField(max_length=200)),
                ('khasiat', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=50)),
                ('alamat', models.TextField(max_length=100)),
                ('keluhan', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('total_harga', models.CharField(max_length=50)),
                ('kumpulan_obat', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='dokter',
            name='jadwal_praktek',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dokter',
            name='nomor_telepon',
            field=models.IntegerField(max_length=20),
        ),
    ]
